### PR TITLE
ranch deploy:conf

### PR DESCRIPTION
**Pull request by bobzoller**
A new command to apply configuration changes (env, scale, cron) to the running code.

Currently, ranch releases are short git SHAs that reference the version of the code that is deployed.  Going forward, ranch release ids will look like `<code sha>-<conf sha>`, to allow us to continue to use git as a control plane, but also be able to apply configuration changes without doing a code push.

So far, this will only benefit developers on their local machines, as CI has no way of telling if it can take the optimized path of a `deploy:conf`, but I can imagine using globs to declare paths that require a code push vs paths that don't.

### CODE REVIEW

**Comment by randypuro** [comment]
Ah, this'll be such a big help. What's the workflow? `ranch env:set` then `ranch deploy:conf`? If there is a ecru deploy queued or in process, is there a risk of the conf being reverted?

**Comment by bobzoller** [comment]
Yes that's the workflow (and env commands will remind you now).  Last
deploy always wins, so this is still a bit of an escape hatch and you need
to understand what your CI pipeline looks like when you use it.

**Comment by asalant** [comment]
Thinking about interface... would `ranch env:deploy` make sense? What else is in the `deploy:` namespace?

**Comment by bobzoller** [comment]
it does more than env -- it does anything in the ranch config file,
currently: env, formation (process list, args, scale), and cron.

I was thinking about `ranch apply` ...  ?  nothing else in the deploy
namespace.

**Pull request merged**
